// Explicit JS-compatible attribute fields; recalculation is in attributes.rs.
#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CombatStats {
    pub attack_interval: f64,
    pub auto_attack_damage: f64,
    pub ability_damage: f64,
    pub critical_rate: f64,
    pub critical_damage: f64,
    pub stab_accuracy: f64,
    pub slash_accuracy: f64,
    pub smash_accuracy: f64,
    pub ranged_accuracy: f64,
    pub magic_accuracy: f64,
    pub stab_damage: f64,
    pub slash_damage: f64,
    pub smash_damage: f64,
    pub ranged_damage: f64,
    pub magic_damage: f64,
    pub defensive_damage: f64,
    pub task_damage: f64,
    pub physical_amplify: f64,
    pub water_amplify: f64,
    pub nature_amplify: f64,
    pub fire_amplify: f64,
    pub healing_amplify: f64,
    pub physical_thorns: f64,
    pub elemental_thorns: f64,
    pub max_hitpoints: f64,
    pub max_manapoints: f64,
    pub stab_evasion: f64,
    pub slash_evasion: f64,
    pub smash_evasion: f64,
    pub ranged_evasion: f64,
    pub magic_evasion: f64,
    pub armor: f64,
    pub water_resistance: f64,
    pub nature_resistance: f64,
    pub fire_resistance: f64,
    pub life_steal: f64,
    pub hp_regen_per10: f64,
    pub mp_regen_per10: f64,
    pub combat_drop_rate: f64,
    pub combat_drop_quantity: f64,
    pub combat_rare_find: f64,
    pub combat_experience: f64,
    pub food_slots: f64,
    pub drink_slots: f64,
    pub armor_penetration: f64,
    pub water_penetration: f64,
    pub nature_penetration: f64,
    pub fire_penetration: f64,
    pub mana_leech: f64,
    pub cast_speed: f64,
    pub threat: f64,
    pub parry: f64,
    pub mayhem: f64,
    pub pierce: f64,
    pub curse: f64,
    pub ripple: f64,
    pub bloom: f64,
    pub blaze: f64,
    pub weaken: f64,
    pub fury: f64,
    pub food_haste: f64,
    pub drink_concentration: f64,
    pub damage_taken: f64,
    pub attack_speed: f64,
    pub armor_damage_ratio: f64,
    pub hp_drain_ratio: f64,
    pub stamina_experience: f64,
    pub intelligence_experience: f64,
    pub attack_experience: f64,
    pub defense_experience: f64,
    pub melee_experience: f64,
    pub ranged_experience: f64,
    pub magic_experience: f64,
    pub retaliation: f64,
    pub max_hitpoints_ratio: f64,
    pub max_manapoints_ratio: f64,
    pub ability_haste: f64,
    pub tenacity: f64,

    pub combat_style_hrid: String,
    pub damage_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub primary_training: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub focus_training: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub combat_style_hrids: Option<Vec<String>>,
}
impl Default for CombatStats {
    fn default() -> Self {
        Self {
            attack_interval: 3000000000.0,
            auto_attack_damage: 0.0,
            ability_damage: 0.0,
            critical_rate: 0.0,
            critical_damage: 0.0,
            stab_accuracy: 0.0,
            slash_accuracy: 0.0,
            smash_accuracy: 0.0,
            ranged_accuracy: 0.0,
            magic_accuracy: 0.0,
            stab_damage: 0.0,
            slash_damage: 0.0,
            smash_damage: 0.0,
            ranged_damage: 0.0,
            magic_damage: 0.0,
            defensive_damage: 0.0,
            task_damage: 0.0,
            physical_amplify: 0.0,
            water_amplify: 0.0,
            nature_amplify: 0.0,
            fire_amplify: 0.0,
            healing_amplify: 0.0,
            physical_thorns: 0.0,
            elemental_thorns: 0.0,
            max_hitpoints: 0.0,
            max_manapoints: 0.0,
            stab_evasion: 0.0,
            slash_evasion: 0.0,
            smash_evasion: 0.0,
            ranged_evasion: 0.0,
            magic_evasion: 0.0,
            armor: 0.0,
            water_resistance: 0.0,
            nature_resistance: 0.0,
            fire_resistance: 0.0,
            life_steal: 0.0,
            hp_regen_per10: 0.01,
            mp_regen_per10: 0.01,
            combat_drop_rate: 0.0,
            combat_drop_quantity: 0.0,
            combat_rare_find: 0.0,
            combat_experience: 0.0,
            food_slots: 1.0,
            drink_slots: 1.0,
            armor_penetration: 0.0,
            water_penetration: 0.0,
            nature_penetration: 0.0,
            fire_penetration: 0.0,
            mana_leech: 0.0,
            cast_speed: 0.0,
            threat: 100.0,
            parry: 0.0,
            mayhem: 0.0,
            pierce: 0.0,
            curse: 0.0,
            ripple: 0.0,
            bloom: 0.0,
            blaze: 0.0,
            weaken: 0.0,
            fury: 0.0,
            food_haste: 0.0,
            drink_concentration: 0.0,
            damage_taken: 0.0,
            attack_speed: 0.0,
            armor_damage_ratio: 0.0,
            hp_drain_ratio: 0.0,
            stamina_experience: 0.0,
            intelligence_experience: 0.0,
            attack_experience: 0.0,
            defense_experience: 0.0,
            melee_experience: 0.0,
            ranged_experience: 0.0,
            magic_experience: 0.0,
            retaliation: 0.0,
            max_hitpoints_ratio: 0.0,
            max_manapoints_ratio: 0.0,
            ability_haste: 0.0,
            tenacity: 0.0,
            combat_style_hrid: "/combat_styles/smash".into(),
            damage_type: "/damage_types/physical".into(),
            primary_training: Some(String::new()),
            focus_training: Some(String::new()),
            combat_style_hrids: None,
        }
    }
}
impl CombatStats {
    pub fn get(&self, key: &str) -> f64 {
        match key {
            "attackInterval" => self.attack_interval,
            "autoAttackDamage" => self.auto_attack_damage,
            "abilityDamage" => self.ability_damage,
            "criticalRate" => self.critical_rate,
            "criticalDamage" => self.critical_damage,
            "stabAccuracy" => self.stab_accuracy,
            "slashAccuracy" => self.slash_accuracy,
            "smashAccuracy" => self.smash_accuracy,
            "rangedAccuracy" => self.ranged_accuracy,
            "magicAccuracy" => self.magic_accuracy,
            "stabDamage" => self.stab_damage,
            "slashDamage" => self.slash_damage,
            "smashDamage" => self.smash_damage,
            "rangedDamage" => self.ranged_damage,
            "magicDamage" => self.magic_damage,
            "defensiveDamage" => self.defensive_damage,
            "taskDamage" => self.task_damage,
            "physicalAmplify" => self.physical_amplify,
            "waterAmplify" => self.water_amplify,
            "natureAmplify" => self.nature_amplify,
            "fireAmplify" => self.fire_amplify,
            "healingAmplify" => self.healing_amplify,
            "physicalThorns" => self.physical_thorns,
            "elementalThorns" => self.elemental_thorns,
            "maxHitpoints" => self.max_hitpoints,
            "maxManapoints" => self.max_manapoints,
            "stabEvasion" => self.stab_evasion,
            "slashEvasion" => self.slash_evasion,
            "smashEvasion" => self.smash_evasion,
            "rangedEvasion" => self.ranged_evasion,
            "magicEvasion" => self.magic_evasion,
            "armor" => self.armor,
            "waterResistance" => self.water_resistance,
            "natureResistance" => self.nature_resistance,
            "fireResistance" => self.fire_resistance,
            "lifeSteal" => self.life_steal,
            "hpRegenPer10" => self.hp_regen_per10,
            "mpRegenPer10" => self.mp_regen_per10,
            "combatDropRate" => self.combat_drop_rate,
            "combatDropQuantity" => self.combat_drop_quantity,
            "combatRareFind" => self.combat_rare_find,
            "combatExperience" => self.combat_experience,
            "foodSlots" => self.food_slots,
            "drinkSlots" => self.drink_slots,
            "armorPenetration" => self.armor_penetration,
            "waterPenetration" => self.water_penetration,
            "naturePenetration" => self.nature_penetration,
            "firePenetration" => self.fire_penetration,
            "manaLeech" => self.mana_leech,
            "castSpeed" => self.cast_speed,
            "threat" => self.threat,
            "parry" => self.parry,
            "mayhem" => self.mayhem,
            "pierce" => self.pierce,
            "curse" => self.curse,
            "ripple" => self.ripple,
            "bloom" => self.bloom,
            "blaze" => self.blaze,
            "weaken" => self.weaken,
            "fury" => self.fury,
            "foodHaste" => self.food_haste,
            "drinkConcentration" => self.drink_concentration,
            "damageTaken" => self.damage_taken,
            "attackSpeed" => self.attack_speed,
            "armorDamageRatio" => self.armor_damage_ratio,
            "hpDrainRatio" => self.hp_drain_ratio,
            "staminaExperience" => self.stamina_experience,
            "intelligenceExperience" => self.intelligence_experience,
            "attackExperience" => self.attack_experience,
            "defenseExperience" => self.defense_experience,
            "meleeExperience" => self.melee_experience,
            "rangedExperience" => self.ranged_experience,
            "magicExperience" => self.magic_experience,
            "retaliation" => self.retaliation,
            "maxHitpointsRatio" => self.max_hitpoints_ratio,
            "maxManapointsRatio" => self.max_manapoints_ratio,
            "abilityHaste" => self.ability_haste,
            "tenacity" => self.tenacity,
            _ => 0.0,
        }
    }
    pub fn set(&mut self, key: &str, value: f64) {
        match key {
            "attackInterval" => self.attack_interval = value,
            "autoAttackDamage" => self.auto_attack_damage = value,
            "abilityDamage" => self.ability_damage = value,
            "criticalRate" => self.critical_rate = value,
            "criticalDamage" => self.critical_damage = value,
            "stabAccuracy" => self.stab_accuracy = value,
            "slashAccuracy" => self.slash_accuracy = value,
            "smashAccuracy" => self.smash_accuracy = value,
            "rangedAccuracy" => self.ranged_accuracy = value,
            "magicAccuracy" => self.magic_accuracy = value,
            "stabDamage" => self.stab_damage = value,
            "slashDamage" => self.slash_damage = value,
            "smashDamage" => self.smash_damage = value,
            "rangedDamage" => self.ranged_damage = value,
            "magicDamage" => self.magic_damage = value,
            "defensiveDamage" => self.defensive_damage = value,
            "taskDamage" => self.task_damage = value,
            "physicalAmplify" => self.physical_amplify = value,
            "waterAmplify" => self.water_amplify = value,
            "natureAmplify" => self.nature_amplify = value,
            "fireAmplify" => self.fire_amplify = value,
            "healingAmplify" => self.healing_amplify = value,
            "physicalThorns" => self.physical_thorns = value,
            "elementalThorns" => self.elemental_thorns = value,
            "maxHitpoints" => self.max_hitpoints = value,
            "maxManapoints" => self.max_manapoints = value,
            "stabEvasion" => self.stab_evasion = value,
            "slashEvasion" => self.slash_evasion = value,
            "smashEvasion" => self.smash_evasion = value,
            "rangedEvasion" => self.ranged_evasion = value,
            "magicEvasion" => self.magic_evasion = value,
            "armor" => self.armor = value,
            "waterResistance" => self.water_resistance = value,
            "natureResistance" => self.nature_resistance = value,
            "fireResistance" => self.fire_resistance = value,
            "lifeSteal" => self.life_steal = value,
            "hpRegenPer10" => self.hp_regen_per10 = value,
            "mpRegenPer10" => self.mp_regen_per10 = value,
            "combatDropRate" => self.combat_drop_rate = value,
            "combatDropQuantity" => self.combat_drop_quantity = value,
            "combatRareFind" => self.combat_rare_find = value,
            "combatExperience" => self.combat_experience = value,
            "foodSlots" => self.food_slots = value,
            "drinkSlots" => self.drink_slots = value,
            "armorPenetration" => self.armor_penetration = value,
            "waterPenetration" => self.water_penetration = value,
            "naturePenetration" => self.nature_penetration = value,
            "firePenetration" => self.fire_penetration = value,
            "manaLeech" => self.mana_leech = value,
            "castSpeed" => self.cast_speed = value,
            "threat" => self.threat = value,
            "parry" => self.parry = value,
            "mayhem" => self.mayhem = value,
            "pierce" => self.pierce = value,
            "curse" => self.curse = value,
            "ripple" => self.ripple = value,
            "bloom" => self.bloom = value,
            "blaze" => self.blaze = value,
            "weaken" => self.weaken = value,
            "fury" => self.fury = value,
            "foodHaste" => self.food_haste = value,
            "drinkConcentration" => self.drink_concentration = value,
            "damageTaken" => self.damage_taken = value,
            "attackSpeed" => self.attack_speed = value,
            "armorDamageRatio" => self.armor_damage_ratio = value,
            "hpDrainRatio" => self.hp_drain_ratio = value,
            "staminaExperience" => self.stamina_experience = value,
            "intelligenceExperience" => self.intelligence_experience = value,
            "attackExperience" => self.attack_experience = value,
            "defenseExperience" => self.defense_experience = value,
            "meleeExperience" => self.melee_experience = value,
            "rangedExperience" => self.ranged_experience = value,
            "magicExperience" => self.magic_experience = value,
            "retaliation" => self.retaliation = value,
            "maxHitpointsRatio" => self.max_hitpoints_ratio = value,
            "maxManapointsRatio" => self.max_manapoints_ratio = value,
            "abilityHaste" => self.ability_haste = value,
            "tenacity" => self.tenacity = value,
            _ => {}
        }
    }
}
#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CombatDetails {
    pub stamina_level: f64,
    pub intelligence_level: f64,
    pub attack_level: f64,
    pub melee_level: f64,
    pub defense_level: f64,
    pub ranged_level: f64,
    pub magic_level: f64,
    pub max_hitpoints: f64,
    pub current_hitpoints: f64,
    pub max_manapoints: f64,
    pub current_manapoints: f64,
    pub stab_accuracy_rating: f64,
    pub slash_accuracy_rating: f64,
    pub smash_accuracy_rating: f64,
    pub ranged_accuracy_rating: f64,
    pub magic_accuracy_rating: f64,
    pub stab_max_damage: f64,
    pub slash_max_damage: f64,
    pub smash_max_damage: f64,
    pub ranged_max_damage: f64,
    pub magic_max_damage: f64,
    pub stab_evasion_rating: f64,
    pub slash_evasion_rating: f64,
    pub smash_evasion_rating: f64,
    pub ranged_evasion_rating: f64,
    pub magic_evasion_rating: f64,
    pub defensive_max_damage: f64,
    pub total_armor: f64,
    pub total_water_resistance: f64,
    pub total_nature_resistance: f64,
    pub total_fire_resistance: f64,
    pub ability_haste: f64,
    pub tenacity: f64,
    pub total_threat: f64,
    pub combat_stats: CombatStats,
}
impl Default for CombatDetails {
    fn default() -> Self {
        Self {
            stamina_level: 1.0,
            intelligence_level: 1.0,
            attack_level: 1.0,
            melee_level: 1.0,
            defense_level: 1.0,
            ranged_level: 1.0,
            magic_level: 1.0,
            max_hitpoints: 110.0,
            current_hitpoints: 110.0,
            max_manapoints: 110.0,
            current_manapoints: 110.0,
            stab_accuracy_rating: 11.0,
            slash_accuracy_rating: 11.0,
            smash_accuracy_rating: 11.0,
            ranged_accuracy_rating: 11.0,
            magic_accuracy_rating: 11.0,
            stab_max_damage: 11.0,
            slash_max_damage: 11.0,
            smash_max_damage: 11.0,
            ranged_max_damage: 11.0,
            magic_max_damage: 11.0,
            stab_evasion_rating: 11.0,
            slash_evasion_rating: 11.0,
            smash_evasion_rating: 11.0,
            ranged_evasion_rating: 11.0,
            magic_evasion_rating: 11.0,
            defensive_max_damage: 0.0,
            total_armor: 0.2,
            total_water_resistance: 0.4,
            total_nature_resistance: 0.4,
            total_fire_resistance: 0.4,
            ability_haste: 0.0,
            tenacity: 0.0,
            total_threat: 100.0,
            combat_stats: CombatStats::default(),
        }
    }
}
pub const EQUIPMENT_STATS: [&str; 70] = [
    "stabAccuracy",
    "slashAccuracy",
    "smashAccuracy",
    "rangedAccuracy",
    "magicAccuracy",
    "stabDamage",
    "slashDamage",
    "smashDamage",
    "rangedDamage",
    "magicDamage",
    "defensiveDamage",
    "taskDamage",
    "physicalAmplify",
    "waterAmplify",
    "natureAmplify",
    "fireAmplify",
    "healingAmplify",
    "stabEvasion",
    "slashEvasion",
    "smashEvasion",
    "rangedEvasion",
    "magicEvasion",
    "armor",
    "waterResistance",
    "natureResistance",
    "fireResistance",
    "maxHitpoints",
    "maxManapoints",
    "lifeSteal",
    "hpRegenPer10",
    "mpRegenPer10",
    "physicalThorns",
    "elementalThorns",
    "combatDropRate",
    "combatRareFind",
    "combatDropQuantity",
    "combatExperience",
    "criticalRate",
    "criticalDamage",
    "armorPenetration",
    "waterPenetration",
    "naturePenetration",
    "firePenetration",
    "abilityHaste",
    "tenacity",
    "manaLeech",
    "castSpeed",
    "threat",
    "parry",
    "mayhem",
    "pierce",
    "curse",
    "fury",
    "weaken",
    "ripple",
    "bloom",
    "blaze",
    "attackSpeed",
    "foodHaste",
    "drinkConcentration",
    "autoAttackDamage",
    "abilityDamage",
    "staminaExperience",
    "intelligenceExperience",
    "attackExperience",
    "defenseExperience",
    "meleeExperience",
    "rangedExperience",
    "magicExperience",
    "retaliation",
];
pub const MONSTER_ZERO_STATS: [&str; 63] = [
    "stabAccuracy",
    "slashAccuracy",
    "smashAccuracy",
    "rangedAccuracy",
    "magicAccuracy",
    "stabDamage",
    "slashDamage",
    "smashDamage",
    "rangedDamage",
    "magicDamage",
    "defensiveDamage",
    "taskDamage",
    "physicalAmplify",
    "waterAmplify",
    "natureAmplify",
    "fireAmplify",
    "healingAmplify",
    "stabEvasion",
    "slashEvasion",
    "smashEvasion",
    "rangedEvasion",
    "magicEvasion",
    "armor",
    "waterResistance",
    "natureResistance",
    "fireResistance",
    "maxHitpoints",
    "maxManapoints",
    "lifeSteal",
    "hpRegenPer10",
    "mpRegenPer10",
    "physicalThorns",
    "elementalThorns",
    "combatDropRate",
    "combatRareFind",
    "combatDropQuantity",
    "combatExperience",
    "criticalRate",
    "criticalDamage",
    "armorPenetration",
    "waterPenetration",
    "naturePenetration",
    "firePenetration",
    "abilityHaste",
    "tenacity",
    "manaLeech",
    "castSpeed",
    "threat",
    "parry",
    "mayhem",
    "pierce",
    "curse",
    "fury",
    "weaken",
    "ripple",
    "bloom",
    "blaze",
    "attackSpeed",
    "foodHaste",
    "drinkConcentration",
    "autoAttackDamage",
    "abilityDamage",
    "retaliation",
];
